blogger_blog_post:
    resource: "@BloggerBlogBundle/Resources/config/routing/post.yml"
    prefix:   /

BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET
